CREATE DATABASE CADASTRO;
USE CADASTRO;

CREATE TABLE TIPO_DE_USUARIO (
    ID_TIPO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE CURSO (
    ID_CURSO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME_CURSO VARCHAR(30) NOT NULL
);

CREATE TABLE MATERIAL_DE_ESTUDOS (
    ID_ESTUDOS INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PDFS VARCHAR(50) NOT NULL,
    VIDEOS VARCHAR(50) NOT NULL,
    MATERIAL VARCHAR(50) NOT NULL,
    ID_CURSO INT NOT NULL, -- Usando ID_CURSO como chave estrangeira
    FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO)
);

CREATE TABLE CARDAPIO (
    ID_CARDAPIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DIA VARCHAR(20) NOT NULL,
    REFEICAO VARCHAR(50) NOT NULL
);

CREATE TABLE USUARIO (
    ID_USUARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DATA_NASC DATE NOT NULL,  -- Corrigido para usar DATE
    MATRICULA INT NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CURSO INT NOT NULL,
    TIPO_USUARIO INT NOT NULL,
    SENHA VARCHAR(255) NOT NULL,  -- Definido um comprimento para a senha (255 é comum)
    FOREIGN KEY (CURSO) REFERENCES CURSO(ID_CURSO),
    FOREIGN KEY (TIPO_USUARIO) REFERENCES TIPO_DE_USUARIO(ID_TIPO)
);

INSERT INTO CURSO (ID_CURSO, NOME_CURSO)
VALUES 
    (1, 'D.S.'),
    (2, 'Logística'),
    (3, 'Administração'),
    (4, 'Recursos Humanos'),
    (5, 'Contabilidade');

INSERT INTO TIPO_DE_USUARIO (ID_TIPO, NOME)
VALUES 
    (1, 'Usuário'),
    (2, 'Administrador');